name = "HDF5Helpers"
uuid = "2867bddc-101e-43c9-836d-7ce2d0afa337"
authors = ["Nils Niggemann <nils.niggemann@fu-berlin.de>"]
version = "0.1.1"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
